//
//  data.swift
//  Valyuta
//
//  Created by Anvarjon Khojimatov on 2022/05/06.
//

import Foundation

let flags: [FlagModel] = [
    FlagModel(currency: "USD", flag: "🇺🇸"),
    FlagModel(currency: "EUR", flag: "🇪🇺"),
    FlagModel(currency: "RUB", flag: "🇷🇺"),
    FlagModel(currency: "GBP", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    FlagModel(currency: "JPY", flag: "🇯🇵"),
    FlagModel(currency: "AZN", flag: "🇦🇿"),
    FlagModel(currency: "BDT", flag: "🇧🇩"),
    FlagModel(currency: "BGN", flag: "🇧🇬"),
    FlagModel(currency: "BHD", flag: "🇧🇭"),
    FlagModel(currency: "BND", flag: "🇧🇳"),
    FlagModel(currency: "BRL", flag: "🇧🇷"),
    FlagModel(currency: "BYN", flag: "🇧🇾"),
    FlagModel(currency: "CAD", flag: "🇨🇦"),
    FlagModel(currency: "CHF", flag: "🇨🇭"),
    FlagModel(currency: "CNY", flag: "🇨🇳"),
    FlagModel(currency: "CUP", flag: "🇨🇺"),
    FlagModel(currency: "CZK", flag: "🇨🇿"),
    FlagModel(currency: "DKK", flag: "🇩🇰"),
    FlagModel(currency: "DZD", flag: "🇩🇿"),
    FlagModel(currency: "EGP", flag: "🇪🇬"),
    FlagModel(currency: "AFN", flag: "🇦🇫"),
    FlagModel(currency: "ARS", flag: "🇦🇷"),
    FlagModel(currency: "GEL", flag: "🇬🇪"),
    FlagModel(currency: "HKD", flag: "🇭🇰"),
    FlagModel(currency: "HUF", flag: "🇭🇺"),
    FlagModel(currency: "IDR", flag: "🇮🇩"),
    FlagModel(currency: "ILS", flag: "🇮🇱"),
    FlagModel(currency: "INR", flag: "🇮🇳"),
    FlagModel(currency: "IQD", flag: "🇮🇶"),
    FlagModel(currency: "IRR", flag: "🇮🇷"),
    FlagModel(currency: "ISK", flag: "🇮🇸"),
    FlagModel(currency: "JOD", flag: "🇯🇴"),
    FlagModel(currency: "AUD", flag: "🇦🇺"),
    FlagModel(currency: "KGS", flag: "🇰🇬"),
    FlagModel(currency: "KHR", flag: "🇰🇭"),
    FlagModel(currency: "KRW", flag: "🇰🇷"),
    FlagModel(currency: "KWD", flag: "🇰🇼"),
    FlagModel(currency: "KZT", flag: "🇰🇿"),
    FlagModel(currency: "LAK", flag: "🇱🇦"),
    FlagModel(currency: "LBP", flag: "🇱🇧"),
    FlagModel(currency: "LYD", flag: "🇱🇾"),
    FlagModel(currency: "MAD", flag: "🇲🇦"),
    FlagModel(currency: "MDL", flag: "🇲🇩"),
    FlagModel(currency: "MMK", flag: "🇲🇲"),
    FlagModel(currency: "MNT", flag: "🇲🇳"),
    FlagModel(currency: "MXN", flag: "🇲🇽"),
    FlagModel(currency: "MYR", flag: "🇲🇾"),
    FlagModel(currency: "NOK", flag: "🇳🇴"),
    FlagModel(currency: "NZD", flag: "🇳🇿"),
    FlagModel(currency: "OMR", flag: "🇴🇲"),
    FlagModel(currency: "PHP", flag: "🇵🇭"),
    FlagModel(currency: "PKR", flag: "🇵🇰"),
    FlagModel(currency: "PLN", flag: "🇵🇱"),
    FlagModel(currency: "QAR", flag: "🇶🇦"),
    FlagModel(currency: "RON", flag: "🇷🇴"),
    FlagModel(currency: "RSD", flag: "🇷🇸"),
    FlagModel(currency: "AMD", flag: "🇦🇲"),
    FlagModel(currency: "SAR", flag: "🇸🇦"),
    FlagModel(currency: "SDG", flag: "🇸🇩"),
    FlagModel(currency: "SEK", flag: "🇸🇪"),
    FlagModel(currency: "SGD", flag: "🇸🇬"),
    FlagModel(currency: "SYP", flag: "🇸🇾"),
    FlagModel(currency: "THB", flag: "🇹🇭"),
    FlagModel(currency: "TJS", flag: "🇹🇯"),
    FlagModel(currency: "TMT", flag: "🇹🇲"),
    FlagModel(currency: "TND", flag: "🇹🇳"),
    FlagModel(currency: "TRY", flag: "🇹🇷"),
    FlagModel(currency: "UAH", flag: "🇺🇦"),
    FlagModel(currency: "AED", flag: "🇦🇪"),
    FlagModel(currency: "UYU", flag: "🇺🇾"),
    FlagModel(currency: "VES", flag: "🇻🇪"),
    FlagModel(currency: "VND", flag: "🇻🇳"),
    FlagModel(currency: "XDR", flag: "🇺🇳"),
    FlagModel(currency: "YER", flag: "🇾🇪"),
    FlagModel(currency: "ZAR", flag: "🇿🇦")
]
